"use strict"
const SPREADSHEET_ID='1DgjZVzpBvd797JLfUfahUt1aG24o6iOJdO0FMIh5Ciw';const SHEETS=['Vocabulary','Communication'];const MAX_ROWS=40;let currentRow=1;let isReading=!1;let isLooping=!1;async function init(){if(SHEETS.length>0){createTabs(SHEETS)}else{document.getElementById('no-sheets').style.display='block';document.getElementById('data-table').style.display='none'}}
function createTabs(sheets){const tabsContainer=document.getElementById('tabs-container');tabsContainer.innerHTML='';sheets.forEach((sheet,index)=>{const tab=document.createElement('div');tab.className='tab';tab.textContent=sheet;tab.addEventListener('click',()=>{stopReading();resetReadButton();document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');fetchData(sheet)});tabsContainer.appendChild(tab);if(index===0){tab.classList.add('active');fetchData(sheet)}})}
async function fetchData(sheetName){const url=`https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:csv&sheet=${sheetName}`;try{const response=await fetch(url);if(!response.ok)throw new Error("Không thể tải dữ liệu.");const data=await response.text();displayData(data);currentRow=1}catch(error){alert("Không thể tải dữ liệu từ Google Sheets: "+error.message)}}
function displayData(csvData){const dataRows=document.getElementById('data-rows');dataRows.innerHTML='';const rows=csvData.split('\n').slice(0,MAX_ROWS+1);rows.forEach((row,index)=>{const tr=document.createElement('tr');row.split(',').forEach(cell=>{const td=document.createElement(index===0?'th':'td');td.textContent=cell.replace(/"/g,'');tr.appendChild(td)});if(index!==0){const actionTd=document.createElement('td');const listenButton=document.createElement('button');listenButton.textContent='Nghe';listenButton.addEventListener('click',()=>readSingleRow(tr));actionTd.appendChild(listenButton);tr.appendChild(actionTd)}
dataRows.appendChild(tr)})}
document.getElementById('read-sequence').addEventListener('click',()=>{if(isReading){stopReading()}else{startReading()}});document.getElementById('loop-toggle').addEventListener('click',()=>{isLooping=!isLooping;document.getElementById('loop-toggle').classList.toggle('active',isLooping);document.getElementById('loop-toggle').textContent=isLooping?"Đang lặp lại":"Lặp lại"});function startReading(){isReading=!0;document.getElementById('read-sequence').textContent="Dừng lại";readRow()}
function stopReading(){isReading=!1;document.getElementById('read-sequence').textContent="Tiếp tục nghe";window.speechSynthesis.cancel()}
function resetReadButton(){const readButton=document.getElementById('read-sequence');readButton.textContent="Nghe";isReading=!1}
function readRow(){const rows=document.querySelectorAll('#data-rows tr');if(!isReading)return;if(currentRow>=rows.length){if(isLooping){currentRow=1}else{stopReading();return}}
rows.forEach(row=>row.classList.remove('active-row'));const currentRowElement=rows[currentRow];currentRowElement.classList.add('active-row');const cells=rows[currentRow].querySelectorAll('td');if(cells.length>=2){const textEnglish=cells[0].textContent;const textVietnamese=cells[2].textContent;speakText(textEnglish,'en-US',0.7,()=>{speakText(textVietnamese,'vi-VN',1,()=>{currentRow++;readRow()})})}}
function readSingleRow(rowElement){const cells=rowElement.querySelectorAll('td');if(cells.length>=2){const textEnglish=cells[0].textContent;const textVietnamese=cells[2].textContent;speakText(textEnglish,'en-US',0.8,()=>{speakText(textVietnamese,'vi-VN',1)})}}
function speakText(text,lang,rate=1,onEndCallback){const utterance=new SpeechSynthesisUtterance(text);utterance.lang=lang;utterance.rate=rate;utterance.onend=onEndCallback;window.speechSynthesis.speak(utterance)}
init()